import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});

const outfitMono = Outfit({
  variable: "--font-outfit-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfitSans.variable} ${outfitMono.variable} antialiased`}
      >
        <div className="md:px-20">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
